
[package]
name = "GRIN_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

ic-cdk = "0.14.0"
ic-cdk-macros = "0.14.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
candid_derive = "0.6.1"
candid = "0.10.4"